name: NPM publish on release 
on: 
  push: 
    tags: 
      - v[0-9].[0-9].[0-9]

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependancies and build
        run: npm install && npm prepack
      - name: Publish package to npm.js
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public